/**
 * Generates packages/core/src/palette.ts: the exact sRGB bytes Chromium
 * paints for every Tailwind v4 palette color. The vendored Tailwind browser
 * build compiles `bg-*` classes in-page; each computed backgroundColor
 * (oklch in v4) is drawn onto a 2D canvas and read back via getImageData —
 * no oklch→sRGB math on our side, correct by construction.
 *
 * Usage: bun run packages/oracle/src/extract-palette.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { chromium } from 'playwright';

const VENDOR_DIR = join(import.meta.dir, '../../../vendor');
const OUT = join(import.meta.dir, '../../core/src/palette.ts');

const HUES = [
  'slate', 'gray', 'zinc', 'neutral', 'stone', 'red', 'orange', 'amber',
  'yellow', 'lime', 'green', 'emerald', 'teal', 'cyan', 'sky', 'blue',
  'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose',
];
const SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];

const names = [...HUES.flatMap((h) => SHADES.map((s) => `${h}-${s}`)), 'black', 'white'];

const tailwind = readFileSync(join(VENDOR_DIR, 'tailwindcss-browser-4.js'), 'utf8');
const divs = names.map((n) => `<div id="c-${n}" class="bg-${n}"></div>`).join('');
const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><script>${tailwind}</script></head>
<body>${divs}<canvas id="cv" width="1" height="1"></canvas><div class="hidden" id="tw-probe"></div></body></html>`;

const browser = await chromium.launch({
  args: ['--font-render-hinting=none', '--force-color-profile=srgb'],
});
const version = browser.version();
const page = await browser.newPage({ viewport: { width: 320, height: 240 }, deviceScaleFactor: 1 });
await page.setContent(html, { waitUntil: 'load' });
await page.waitForFunction(() => {
  const probe = document.getElementById('tw-probe');
  return !probe || getComputedStyle(probe).display === 'none';
});

const colors = await page.evaluate((list: string[]) => {
  const cv = document.getElementById('cv') as HTMLCanvasElement;
  const ctx = cv.getContext('2d', { willReadFrequently: true })!;
  const out: Record<string, string> = {};
  for (const name of list) {
    const el = document.getElementById(`c-${name}`)!;
    const css = getComputedStyle(el).backgroundColor;
    ctx.clearRect(0, 0, 1, 1);
    ctx.fillStyle = css;
    ctx.fillRect(0, 0, 1, 1);
    const [r, g, b] = ctx.getImageData(0, 0, 1, 1).data;
    out[name] = `#${[r, g, b].map((v) => v.toString(16).padStart(2, '0')).join('')}`;
  }
  return out;
}, names);

await browser.close();

const missing = names.filter((n) => !colors[n]);
if (missing.length > 0) throw new Error(`palette extraction missed: ${missing.join(', ')}`);

const entries = names.map((n) => `  '${n}': '${colors[n]}',`).join('\n');
writeFileSync(
  OUT,
  `// GENERATED by packages/oracle/src/extract-palette.ts — do not edit.
// sRGB as painted by Chromium ${version} (canvas getImageData, sRGB profile).
export const PALETTE: Record<string, string> = {
${entries}
};
`,
);
console.log(`palette.ts: ${names.length} colors (chromium ${version})`);
